import { ArrowRight, Layers3, Eye, Code2 } from "lucide-react";

export default function About() {
  return (
    <div className="page inner-page">
      <section className="inner-hero compact">
        <span className="pill"><span className="pill-dot" /> About VisionTrace</span>
        <h1>Learn computer vision<br /><em>by seeing it happen.</em></h1>
        <p>VisionTrace is an academic Image & Video Analytics project designed to make algorithmic pipelines easier to understand.</p>
      </section>

      <div className="about-grid">
        <article className="info-card">
          <div className="info-icon"><Eye /></div>
          <span className="eyebrow">01 · Visual learning</span>
          <h3>Intermediate results matter.</h3>
          <p>Instead of hiding the processing behind a button, VisionTrace exposes meaningful stages such as preprocessing, feature extraction, embeddings and matching.</p>
        </article>
        <article className="info-card">
          <div className="info-icon"><Layers3 /></div>
          <span className="eyebrow">02 · Four pipelines</span>
          <h3>Classical + deep learning.</h3>
          <p>Compare a classical technique such as Viola–Jones with modern facial-analysis approaches such as DeepFace and FaceNet.</p>
        </article>
        <article className="info-card">
          <div className="info-icon"><Code2 /></div>
          <span className="eyebrow">03 · Built to demonstrate</span>
          <h3>Actual processing, not mockups.</h3>
          <p>The frontend communicates with a Python backend so the visual results are generated by real computer-vision operations.</p>
        </article>
      </div>

      <div className="about-callout">
        <div>
          <span className="eyebrow">Core idea</span>
          <h2>Input → Process → Visualize → Understand</h2>
        </div>
        <ArrowRight />
      </div>
    </div>
  );
}
